# Generated by Django 5.2.3 on 2025-07-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='N/A', max_length=30),
        ),
    ]
